/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-09-14 04:26:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    boolean loginError = false;

    if("POST".equalsIgnoreCase(request.getMethod())){
        String username = request.getParameter("username");
        String password = request.getParameter("password");

        final String DEFAULT_USERNAME = "admin";
        final String DEFAULT_PASSWORD = "##Admin";

        if(DEFAULT_USERNAME.equals(username) && DEFAULT_PASSWORD.equals(password)){
            response.sendRedirect(request.getContextPath() + "/dashboard.jsp");
            return;
        } else {
            loginError = true;
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SecureBank - Modern Banking Solutions</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("     <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-dark: #1b5e20;\r\n");
      out.write("            --primary: #2e7d32;\r\n");
      out.write("            --primary-light: #4caf50;\r\n");
      out.write("            --primary-lighter: #81c784;\r\n");
      out.write("            --primary-lightest: #e8f5e9;\r\n");
      out.write("            --white: #ffffff;\r\n");
      out.write("            --gray-light: #f5f5f5;\r\n");
      out.write("            --text-dark: #333333;\r\n");
      out.write("            --text-light: #666666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary-lightest) 0%, var(--white) 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animated background elements */\r\n");
      out.write("        .bg-bubbles {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: rgba(76, 175, 80, 0.15);\r\n");
      out.write("            bottom: -160px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: square 25s infinite;\r\n");
      out.write("            transition-timing-function: linear;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(1) {\r\n");
      out.write("            left: 10%;\r\n");
      out.write("            animation-delay: 0s;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(2) {\r\n");
      out.write("            left: 20%;\r\n");
      out.write("            animation-delay: 2s;\r\n");
      out.write("            animation-duration: 17s;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(3) {\r\n");
      out.write("            left: 25%;\r\n");
      out.write("            animation-delay: 4s;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(4) {\r\n");
      out.write("            left: 40%;\r\n");
      out.write("            animation-delay: 0s;\r\n");
      out.write("            animation-duration: 22s;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            height: 120px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(5) {\r\n");
      out.write("            left: 70%;\r\n");
      out.write("            animation-delay: 3s;\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(6) {\r\n");
      out.write("            left: 80%;\r\n");
      out.write("            animation-delay: 2s;\r\n");
      out.write("            width: 90px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(7) {\r\n");
      out.write("            left: 32%;\r\n");
      out.write("            animation-delay: 6s;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 150px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(8) {\r\n");
      out.write("            left: 55%;\r\n");
      out.write("            animation-delay: 8s;\r\n");
      out.write("            animation-duration: 18s;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(9) {\r\n");
      out.write("            left: 25%;\r\n");
      out.write("            animation-delay: 9s;\r\n");
      out.write("            animation-duration: 20s;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-bubbles li:nth-child(10) {\r\n");
      out.write("            left: 85%;\r\n");
      out.write("            animation-delay: 11s;\r\n");
      out.write("            width: 110px;\r\n");
      out.write("            height: 110px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes square {\r\n");
      out.write("            0% {\r\n");
      out.write("                transform: translateY(0) rotate(0deg);\r\n");
      out.write("                opacity: 0.5;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("            }\r\n");
      out.write("            100% {\r\n");
      out.write("                transform: translateY(-1000px) rotate(720deg);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background: linear-gradient(90deg, var(--primary-dark) 0%, var(--primary) 100%);\r\n");
      out.write("            color: var(--white);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo i {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h1 {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav a {\r\n");
      out.write("            color: var(--white);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav a:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 4rem 2rem;\r\n");
      out.write("            height: 90vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero h2 {\r\n");
      out.write("            margin-top: 3%;\r\n");
      out.write("            font-size: 3.5em;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 0 auto 2rem;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: var(--white);\r\n");
      out.write("            padding: 0.8rem 2rem;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border: 2px solid var(--primary);\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(46, 125, 50, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background: var(--white);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(46, 125, 50, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            border-color: var(--primary-dark);\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(27, 94, 32, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login:hover {\r\n");
      out.write("            background: var(--white);\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(27, 94, 32, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .features {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(31, 97, 35, 0.1);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            border: 1px solid rgba(76, 175, 80, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 12px 36px rgba(31, 97, 35, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card i {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card h3 {\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card p {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .piggy-bank-img {\r\n");
      out.write("            max-width: 180px;\r\n");
      out.write("            margin: 1.5rem auto;\r\n");
      out.write("            display: block;\r\n");
      out.write("            filter: drop-shadow(0 5px 15px rgba(0, 0, 0, 0.1));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            color: var(--white);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer p {\r\n");
      out.write("            margin: 0.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            header {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            nav ul {\r\n");
      out.write("                margin-top: 1rem;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero h2 {\r\n");
      out.write("                font-size: 2.2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .features {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Login Form Styling */\r\n");
      out.write("        .login-container {\r\n");
      out.write("            display: ");
      out.print( loginError ? "flex" : "none" );
      out.write(";\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-form {\r\n");
      out.write("            background: var(--white);\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-form h2 {\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0.8rem;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn {\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 0.8rem 1.5rem;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn:hover {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close-login {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close-login:hover {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Background bubbles -->\r\n");
      out.write("    <ul class=\"bg-bubbles\">\r\n");
      out.write("        <li></li><li></li><li></li><li></li><li></li>\r\n");
      out.write("        <li></li><li></li><li></li><li></li><li></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <i class=\"fas fa-piggy-bank\"></i>\r\n");
      out.write("            <h1>SecureBank</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-home\"></i> Home</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-info-circle\"></i> About</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-envelope\"></i> Contact</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick=\"openLogin(); return false;\"><i class=\"fas fa-sign-in-alt\"></i> Login</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero\">\r\n");
      out.write("        <h2>Smart Banking Management</h2>\r\n");
      out.write("        <p>Efficiently manage customers, accounts, and transactions with our simple and secure banking management system designed for financial institutions.</p>\r\n");
      out.write("        <a href=\"#\" onclick=\"openLogin(); return false;\" class=\"btn btn-login\"><i class=\"fas fa-sign-in-alt\"></i> Staff Login</a>\r\n");
      out.write("        <img src=\"img/piggy.png\" height=\"300\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"features\">\r\n");
      out.write("        <!-- Feature cards go here -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-container\" id=\"loginContainer\">\r\n");
      out.write("        <div class=\"login-form\">\r\n");
      out.write("            <h2><i class=\"fas fa-lock\"></i> Staff Login</h2>\r\n");
      out.write("            <form method=\"POST\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"username\">Username</label>\r\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Password</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <button type=\"button\" class=\"close-login\" onclick=\"closeLogin()\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"login-btn\">Login</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 if(loginError) { 
      out.write("\r\n");
      out.write("                    <p style=\"color:red; font-weight:bold; margin-top:10px;\">\r\n");
      out.write("                        Invalid username or password. Please try again.\r\n");
      out.write("                    </p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2023 Smart Bank Management System. All rights reserved.</p>\r\n");
      out.write("        <p>Secure Banking Technology</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function openLogin() {\r\n");
      out.write("            document.getElementById('loginContainer').style.display = 'flex';\r\n");
      out.write("        }\r\n");
      out.write("        function closeLogin() {\r\n");
      out.write("            document.getElementById('loginContainer').style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            const loginContainer = document.getElementById('loginContainer');\r\n");
      out.write("            if (event.target === loginContainer) closeLogin();\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
